[Feat] : 사용자, 채팅, 에이전트, 대화방 도메인 모델 구현
Team-Usay/usay-server pull request #6
Opened 2024-04-04 17:07 UTC by loveysuby

## #️⃣연관된 이슈

> #5 

## 📝작업 내용
- 기존 `질문`, `답변` 도메인은 아래 이유를 고려해서 `대화`로 통합했습니다.
  - 발화 주체의 변동이 가능한 점
  - `면접` 환경 특성상  `대화`의 유형이 질문, 답변 판단 기준이 모호한 점
  - 특정 대화를 조작하지 않고 대화방 단위로 대화 도메인을 관리해야 하는 요구사항을 반영
 
- ref : [ER Diagram](https://github.com/Team-Usay/usay-docs/wiki/ER-Diagram)

## 💬 후속 작업사항
- 각 도메인 별 Unit test를 작성해봤는데, Agent, Member의 Cascade 전략이 결정된 후에 `수정`, `삭제`에 대한 테스트를 작성할 수 있다.
- 파일 구조를 도메인 단위로 구성했는데, 파일 구조나 커밋, 어노테이션 등 규격화 가능한 요소에 대한 convention이 필요하다.
- PR template이 추가되어 있지 않아서, 기존에 사용하던 거 가져왔는데 가독성 관점에서  부탁하다 코멘트 😎

2024-04-05 06:11 UTC, woosung1223 requested changes
고생하셨습니다.. 크게 어려운 리뷰는 아니고 단순 수정만 해주시면 좋을 것 같습니다.. 리뷰 적게 달려고 했는데 엔티티나 스키마는 프로젝트의 기반이라 중요한 부분이라 달게 되었심다..

PR 템플릿 ERD 마음에 드네요 굿 PR 템플릿은 main 브랜치에 넣어주시죠!

2024-04-05 06:11 UTC, woosung1223 commented on src/main/java/usay/app/domain/agent/entity/Agent.java
> +	@NonNull
lombok의 NotNull보다는 javax의 `@NotNull`을 이용하거나, `@Column(nullable = false)`를 활용하는게 좋을 것 같아요.

1. Lombok을 사용하는 경우, Hibernate에서 인식할 수 없어 테스트 등에서 테이블 자동 생성 시 not null 제약조건이 부여되지 않습니다.
2. Lombok은 크게 중요하지 않은 외부 의존성이므로 최대한 약결합을 유지해야 한다고 생각합니다.

2024-04-05 06:11 UTC, woosung1223 commented on src/main/java/usay/app/domain/agent/entity/Agent.java
> +	@OneToMany(mappedBy = "agent", orphanRemoval = true)
`CASCADE` 속성을 부여하는 것에 대해서는 어떻게 생각하시나요? (`orphanRemoval`이 달려 있어서..)

2024-04-05 06:11 UTC, woosung1223 commented on src/main/java/usay/app/domain/agent/entity/Agent.java
> +	@Builder
name, difficulty, about 필드는 모두 notnull이므로 빌더가 필요하지 않은 것 같습니다.

필드가 많고 선택적으로 필드를 초기화해야 하는 경우 빌더가 유용하게 사용될 수 있지만요! 이 경우는 효용이 크게 느껴지지 않네요.

[대충 이펙티브 자바 링크](https://velog.io/@lychee/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EC%95%84%EC%9D%B4%ED%85%9C-2.-%EC%83%9D%EC%84%B1%EC%9E%90%EC%97%90-%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98%EA%B0%80-%EB%A7%8E%EB%8B%A4%EB%A9%B4-%EB%B9%8C%EB%8D%94%EB%A5%BC-%EA%B3%A0%EB%A0%A4%ED%95%98%EB%9D%BC)

2024-04-05 06:11 UTC, woosung1223 commented on src/main/java/usay/app/domain/chat/entity/Chat.java
> +	@Column(name = "chat_id")
Chat 엔티티만 PK 컬럼명이 chat_id네요!

일관성을 위해 PK는 `ID`로 통일하는 건 어떨까요?

2024-04-05 06:11 UTC, woosung1223 commented on src/main/java/usay/app/domain/member/entity/Member.java
> +	@Column(name = "member_id")
여기도 마찬가지입니다!

2024-04-05 06:11 UTC, woosung1223 commented on src/main/resources/db/data.sql
> +
👨‍👨‍👦

2024-04-05 06:11 UTC, woosung1223 commented on src/main/resources/db/schema.sql
> +    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
`ON UPDATE CURRENT_TIMESTAMP`는 JPA에서 알아서 updated_at을 수정해주니까 달지 않아도 될 거 같은데 어케 생각하십니까?

2024-04-05 06:11 UTC, woosung1223 commented on src/main/java/usay/app/common/entity/BaseEntity.java
> +	private LocalDateTime updatedAt;
여기도 `nullable = false` 들어가면 좋을거같심다

2024-04-05 06:11 UTC, woosung1223 commented on src/main/resources/db/schema.sql
> +    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
추가로 NOT NULL 제약조건도 부여되면 좋을거같네여~ (score도)

2024-04-05 06:11 UTC, woosung1223 commented on src/main/resources/db/schema.sql
> +    name       VARCHAR(50) NOT NULL,
VARCHAR는 아직 비즈니스적으로 정해진 게 없으니 255로 고정하는 것이 나아보이는데 어떻게 생각하시는지..

2024-04-05 06:17 UTC, loveysuby commented on src/main/java/usay/app/common/entity/BaseEntity.java
> +	private LocalDateTime updatedAt;
h2 상에서 로컬 테스트를 시행했었는데, 이때 `@CreateDate`로 지정한 필드는 주입이 되지 않음을 확인했습니다.
이제 외부에서 `data.sql`로 더미 데이터를 주입받지 않기 때문에, 추가해도 무방할 것 같네요. 반영하겠습니다

2024-04-05 06:21 UTC, loveysuby commented on src/main/resources/db/schema.sql
> +    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
`application.yml`에서 설정을 뺀 상태라서 별도 수정을 진행하진 않았었어요
`jpa`로 생성하는 테이블과 `schema.sql`의 시행 결과가 같아야해서 우선 not null만 달아두고 schema.sql을 사용하여 테이블을 생성하게 될 때를 대비해서 NOT NULL 제약 조건은 추가해두는 게 맞다고 생각합니다.

2024-04-05 06:26 UTC, loveysuby commented on src/main/java/usay/app/domain/agent/entity/Agent.java
> +	@OneToMany(mappedBy = "agent", orphanRemoval = true)
이 부분은 "대화 모델이 서비스 중간에 삭제(지원중단)되면, 해당 모델을 사용했던 대화방을 삭제해야 할지" 명시적으로 결정된 부분이 없어서 제외했어요. 
개인적인 의견을 첨언하자면, 면접 대화가 마무리 될 때 해당 대화방에서는 더 이상 채팅을 진행할 수 없으므로, `CascadeType.ALL` 을 부여해서 삭제하는 것이 낫다고 보았는데 어떠신가요 ? 
이전 대화 기록을 저장해두어야 하는 `면접기록 열람` 기능에 대한 논의에서 Cascade 전략을 차후 조정하면 될 것 같아요.

2024-04-05 06:29 UTC, woosung1223 commented on src/main/java/usay/app/domain/agent/entity/Agent.java
> +	@OneToMany(mappedBy = "agent", orphanRemoval = true)
굿굿굿 좋은 근거입니다 👶

말씀주신대로 Cascade에 대한 논의는 지금 할 필요는 없을 것 같아요! (비즈니스적으로 정해진 바가 없으므로)
비슷하게 양방향 매핑도 지금은 일단 내비두고, 다대일 관계만 두는건 어떠신가요?

2024-04-05 07:38 UTC, merged

2024-04-11 10:26 UTC, loveysuby commented on src/main/java/usay/app/domain/agent/entity/Agent.java
> +	@OneToMany(mappedBy = "agent", orphanRemoval = true)
이거 바꿔놨었는데 코멘트를 늦게 확인했네요. 
`@OneToMany`로 맺어뒀던 관계들을 일단 빼고, 다대일만 엮어두었습니다. 2차 스프린트에서 다시 리마인드 하겠습니다 👶

2024-04-11 10:26 UTC, loveysuby commented on src/main/java/usay/app/domain/chat/entity/Chat.java
> +	@Column(name = "chat_id")
전부 반영했습니다 👶

2024-04-11 10:29 UTC, loveysuby commented on src/main/resources/db/schema.sql
> +    name       VARCHAR(50) NOT NULL,
같은 의견입니다. 특히나 유저의 가입 방법에 대한 플로우가 낮은 우선순위를 가지고 있으므로, 50으로 두면 이후 기능 개발에 있어 잠재된 문제점이 될 수 있겠네요. 다음 스프린트에서 같이 수정하겠습니다 👶